const vehicleData = [
  {
    LicensePlate: "6TRJ244",
    year: "2017",
    make: "Toyota",
    model: "Prius",
    vin: "JTDKBRFU9J30593O7",
    status: "Active",
    type: "Car",
    group: "Management",
    currentMeter: "20.811 mi",
    operator: {
      name: "Jacob Silva",
    },
    hasFuelCard: "N",
  },
  {
    LicensePlate: "6PRJ609",
    year: "2020",
    make: "Maruti",
    model: "Prius",
    vin: "JTDKKYGU9J3059380",
    status: "Inactive",
    type: "Car",
    group: "Management",
    currentMeter: "22.900 mi",
    operator: {
      name: "Jacob",
    },
    hasFuelCard: "N",
  },
  {
    LicensePlate: "6PRJ680",
    year: "2021",
    make: "Tata",
    model: "Prius",
    vin: "JTDKKYGU9J3059500",
    status: "Active",
    type: "Truck",
    group: "Staff",
    currentMeter: "22.900 mi",
    operator: {
      name: "Silva",
    },
    hasFuelCard: "Y",
  },
  {
    LicensePlate: "6ABC123",
    year: "2018",
    make: "Ford",
    model: "Fusion",
    vin: "ABCDEF12345678901",
    status: "Active",
    type: "Car",
    group: "Management",
    currentMeter: "25.500 mi",
    operator: {
      name: "Alice Johnson",
    },
    hasFuelCard: "Y",
  },
  {
    LicensePlate: "6XYZ789",
    year: "2019",
    make: "Chevrolet",
    model: "Silverado",
    vin: "XYZ789ABC12345678",
    status: "Inactive",
    type: "Truck",
    group: "Management",
    currentMeter: "30.200 mi",
    operator: {
      name: "Bob Anderson",
    },
    hasFuelCard: "N",
  },
  {
    LicensePlate: "6LMN456",
    year: "2022",
    make: "Honda",
    model: "Civic",
    vin: "LMN456XYZ78901234",
    status: "Active",
    type: "Car",
    group: "Staff",
    currentMeter: "18.700 mi",
    operator: {
      name: "Eva Rodriguez",
    },
    hasFuelCard: "N",
  },
  {
    LicensePlate: "6ABC123",
    year: "2018",
    make: "Ford",
    model: "Fusion",
    vin: "ABCDEF12345678901",
    status: "Active",
    type: "Car",
    group: "Management",
    currentMeter: "25.500 mi",
    operator: {
      name: "Alice Johnson",
    },
    hasFuelCard: "Y",
  },
  {
    LicensePlate: "6TRJ244",
    year: "2017",
    make: "Toyota",
    model: "Prius",
    vin: "JTDKBRFU9J30593O7",
    status: "Active",
    type: "Car",
    group: "Management",
    currentMeter: "20.811 mi",
    operator: {
      name: "Jacob Silva",
    },
    hasFuelCard: "N",
  },
  {
    LicensePlate: "6PRJ609",
    year: "2020",
    make: "Maruti",
    model: "Prius",
    vin: "JTDKKYGU9J3059380",
    status: "Inactive",
    type: "Car",
    group: "Management",
    currentMeter: "22.900 mi",
    operator: {
      name: "Jacob",
    },
    hasFuelCard: "N",
  },
  {
    LicensePlate: "6PRJ680",
    year: "2021",
    make: "Tata",
    model: "Prius",
    vin: "JTDKKYGU9J3059500",
    status: "Active",
    type: "Truck",
    group: "Staff",
    currentMeter: "22.900 mi",
    operator: {
      name: "Silva",
    },
    hasFuelCard: "Y",
  },
  {
    LicensePlate: "6ABC123",
    year: "2018",
    make: "Ford",
    model: "Fusion",
    vin: "ABCDEF12345678901",
    status: "Active",
    type: "Car",
    group: "Management",
    currentMeter: "25.500 mi",
    operator: {
      name: "Alice Johnson",
    },
    hasFuelCard: "Y",
  },
  {
    LicensePlate: "6XYZ789",
    year: "2019",
    make: "Chevrolet",
    model: "Silverado",
    vin: "XYZ789ABC12345678",
    status: "Inactive",
    type: "Truck",
    group: "Management",
    currentMeter: "30.200 mi",
    operator: {
      name: "Bob Anderson",
    },
    hasFuelCard: "N",
  },
  {
    LicensePlate: "6LMN456",
    year: "2022",
    make: "Honda",
    model: "Civic",
    vin: "LMN456XYZ78901234",
    status: "Active",
    type: "Car",
    group: "Staff",
    currentMeter: "18.700 mi",
    operator: {
      name: "Eva Rodriguez",
    },
    hasFuelCard: "N",
  },
  {
    LicensePlate: "6ABC123",
    year: "2018",
    make: "Ford",
    model: "Fusion",
    vin: "ABCDEF12345678901",
    status: "Active",
    type: "Car",
    group: "Management",
    currentMeter: "25.500 mi",
    operator: {
      name: "Alice Johnson",
    },
    hasFuelCard: "Y",
  },
];

export default vehicleData;
